### ISSUE TITLE
Question about the target score calculation in `greedy_decoding()`

### ISSUE THREAD

**Issue by OUTHIM** [LHRYANG/Generalization_of_FT-LLM#3]
Hi, thank you for your inspiring work. I may misunderstand part of your code. Thanks ahead for your explanation!

## Q1
In the `greedy_decoding()` function (in `evaluate_cross.py`), it seems that the target score will only be calculated at [the **first** decoding step](https://github.com/LHRYANG/Generalization_of_FT-LLM/blob/f3718fc8ebbef352441ace9c0b74fe316e9cd349/evaluate_cross.py#L43C1-L44C60). Since the function only returns the target score, why do you need to run the decoding of the rest of the steps?

## Q2
Some pre-defined labels can consist of multiple tokens(instead of the only first token). How do you calculate the score of these labels?

**Comment by LHRYANG** [comment]
Thanks for your question. For Q1,  the reason for running the rest of the steps is to observe its output conveniently.  The number of generation steps is very small (e.g., 5) for classification tasks, so it will not take much time. It should also be mentioned the models use BPE encoding, so one word may be split into several subwords, so we output several tokens. 

For Q2, in our implementation, we just use the first token of these labels, since most of the time, different labels have different first tokens.

**Comment by OUTHIM** [comment]
Hi, thanks for clarifying for me. I will close the issue 😁.
